### PR TITLE
Fix: Make stop_id optional in Facility

### PR DESCRIPTION
**Pull request by EmmaSimon**
**Summary:**

We have an entry in our facilities.txt which has no associated stop (it's in the office building), and so doesn't include a stop_id. This makes the id optional so that onebusaway doesn't throw an exception when trying to load the facilities.

**Expected behavior:** 

When loading a facilities.txt file with an empty stop_id, instead of throwing an exception, allow it and just don't load the Stop object for that entry.

Ticket: [Fix missing facility ID issue](https://app.asana.com/0/1204355099788517/1204481224292166/f)

### CODE REVIEW

**Review by lboyarsky — COMMENTED** [review]
The changes look good, but can you give some more context? Is it new functionality to load data from this file? If yes, then it makes sense; If not, I'm wondering how the previous version managed to handle this process.

**Comment by EmmaSimon** [comment]
Yes, the previous version of onebusaway that we were using had no Facility class or handling of any of the facility related GTFS files (they're still experimental). I'm still not certain if OTP is using any of this data, but it's using onebusaway to load all of the GTFS data while building the graph.

**Comment by lboyarsky** [comment]
Based on our own documentation found here: https://github.com/mbta/gtfs-documentation/blob/master/reference/gtfs.md#facilitiestxt, it seems that the stop_id is expected to be included in the file, which suggests that it is a mandatory field. Considering this, should we be focusing on fixing the data source instead?

**Comment by EmmaSimon** [comment]
Yeah I was trying to find the official spec for the facilities information and it seems like we may be the ones who created it? Since that entry does genuinely have no stop associated with it, it seems like stopless facilities might be a valid use case, should we change the spec to be `Included (some records)` instead? @jfabi also brought up the possibility of just assigning it the stop_id of the bus stop outside of the office, which seems a bit hacky, but definitely doable.

**Review by lboyarsky — APPROVED** [review]

**Pull request merged**
